os: osx
os_image: xcode 10.2

langauge: bash

before_install:
  - whoami
  - echo "Start of pipeline"
  - HOMEBREW_NO_AUTO_UPDATE=1

script:
  - ls
  - chmod +x hello.sh

after_script:
  - echo "End of pipeline"
