os: osx
osx_image: code10.2

language: bash

git:
  depth: false

before_cache:
  - brew cleanup

cache:
  - directories:
    - $HOME/Library/Caches/Homebrew

before_install:
  - whoami
  - echo "Start of pipeline"
  - HOMEBREW_NO_AUTO_UPDATE=1

script:
  - ls
  - chmod +x hello.sh
  - docker pull scratch

after_script:
  - echo "End of pipeline"
